### ISSUE TITLE
Can't run this repo

### ISSUE THREAD

**Issue by JavascriptNinja815** [jmptable/derby#2]
when I input `node derby.js`, the below errors have occurred.

![screenshot at jun 04 15-44-23](https://user-images.githubusercontent.com/35192503/40924068-4a3b04fc-680e-11e8-9286-f44d077b2145.png)

Please guid me 
Thanks.

**Comment by jmpinit** [comment]
Hello,

Thanks for trying to run the code.

Port 80 is privileged and is what the code was trying to use by default. An unprivileged user cannot run services on that port.

I've updated the code to use an unprivileged port so it should work for you now.
